### PR TITLE
Update the alpha mods page

### PR DESCRIPTION
**Pull request by loco-choco**
* Changed the available alpha mods
* Changed the installer from DIMOWA to BepInEx

### CODE REVIEW

**Review by Raicuparta — CHANGES_REQUESTED** [review]
Great! A couple requests:
- Can you make `BepInEx` be a link to their repo? You can copy how links are made from `link-list.svelte`.
- Could you add the `isNarrow` property to the sections in this page? I forgot to do it and they're too wide now. It's the same that I already did in the mod manager page.

**Comment by Raicuparta** [comment]
To make the BepInEx link you can either move the description from the property to a separate element, or just add a new item on the top of the list. Let me know if anything is confusing.

**Comment by loco-choco** [comment]
I'll make some other changes, so if you could wait for them I would appreciate it!

**Comment by loco-choco** [comment]
I think all the changes I wanted to do are done, what do you thing about them?

**Pull request merged**
